# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "release/2.0.0-alpha" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    env:
      XCODE_SCHEME: 'PUSDK-Package'
      XCODE_DESTINATION: 'platform=iOS Simulator,OS=16.2,name=iPhone 14'

    runs-on: macos-latest

    steps:
    - name: Checkout the code
      actions/checkout@v3

    - name: Build
      run: xcodebuild \
        -scheme ${{env.XCODE_SCHEME}} \
        -destination ${{env.XCODE_DESTINATION}}

    - name: Show eligible build destinations
      run: xcodebuild -showdestinations -scheme PUSDK-Package

    - name: Run tests
      run: xcodebuild \
        -test \
        -scheme ${{env.XCODE_SCHEME}} \
        -destination ${{env.XCODE_DESTINATION}}
        -testLanguage en \
        -testRegion en_US
