name: publish
on:
  push:
    tags:
    - '*'
    
jobs:
  build:
  runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Publish to CocoaPod trunk
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push PayULite.podspec